PruebaFact/Models/Pago.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PruebaFact.Models
{
    public enum TipoPago
    {
        Efectivo, Cheque, Tarjeta
    }

    public class Pago
    {
        [Required, Display(Name = "Id Pago")]
        public int ID { get; set; }

        [Required, Display(Name = "Tipo de Pago")]
        public TipoPago? TipoPago { get; set; }

        [Required, DataType(DataType.Currency), Display(Name = "Valor")]
        public Decimal Valor { get; set; }

        public virtual Factura Factura { get; set; }
    }
}

PruebaFact/Controllers/FacturaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PruebaFact.DAL;
using PruebaFact.Models;
using PruebaFact.ViewModels;
using PagedList;
using static PruebaFact.Models.EnumAlert;

namespace PruebaFact.Controllers
{
    public class FacturaController : BaseController
    {
        private FacturaContext db = new FacturaContext();

        // GET: Factura
        public ActionResult Index(
            string sortOrder,
            string actgualNumeroFactura,
            string busquedaNumeroFactura,
            string actgualEstablecimiento,
            string busquedaEstablecimiento,
            int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FechaEmisionSortParm = String.IsNullOrEmpty(sortOrder) ? "Date" : "";
            ViewBag.NumeroFacturaSortParm = sortOrder == "id" ? "id_desc" : "id";

            if (busquedaNumeroFactura != null || busquedaEstablecimiento != null)
            {
                page = 1;
            }
            else
            {
                busquedaNumeroFactura = actgualNumeroFactura;
                busquedaEstablecimiento = actgualEstablecimiento;
            }

            ViewBag.actgualNumeroFactura = busquedaNumeroFactura;
            ViewBag.actgualEstablecimiento = busquedaEstablecimiento;

            var facturas = from s in db.Facturas
                        select s;

            if (!String.IsNullOrEmpty(busquedaNumeroFactura))
                facturas = facturas.Where(s => s.ID.ToString().Contains(busquedaNumeroFactura));

            if (!String.IsNullOrEmpty(busquedaEstablecimiento))
                facturas = facturas.Where(s => s.Establecimiento.Contains(busquedaEstablecimiento));

            switch (sortOrder)
            {
                case "id":
                    facturas = facturas.OrderBy(s => s.ID);
                    break;
                case "id_desc":
                    facturas = facturas.OrderByDescending(s => s.ID);
                    break;
                case "Date":
                    facturas = facturas.OrderBy(s => s.FechaEmision);
                    break;
                default:
                    facturas = facturas.OrderByDescending(s => s.FechaEmision);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(facturas.ToPagedList(pageNumber, pageSize));
        }

        // GET: Factura/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Factura factura = db.Facturas.Find(id);
            if (factura == null)
            {
                return HttpNotFound();
            }
            return View(factura);
        }

        // GET: Factura/Create
        public ActionResult Create()
        {
            var factura = new Factura();
            factura.Guias = new List<Guia>();
            GuiasAsignadasData(factura.ID);
            PagosAsignadosData(factura.ID);
            return View();
        }

        // POST: Factura/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Establecimiento,PuntoEmision,Secuencial,FechaEmision,Subtotal,Impuesto,Total")] Factura factura, string[] guiasSeleccionadas, string[] pagosSeleccionados)
        {
            if (guiasSeleccionadas != null) 
            {
                factura.Guias = new List<Guia>();
                foreach (var guiaId in guiasSeleccionadas)
                {
                    var guia = db.Guias.Find(int.Parse(guiaId));
                    factura.Guias.Add(guia);
                }
            }

            if (pagosSeleccionados != null)
            {
                factura.Pagos = new List<Pago>();
                foreach (var pagoId in pagosSeleccionados)
                {
                    var pago = db.Pagos.Find(int.Parse(pagoId));
                    factura.Pagos.Add(pago);
                }
            }

            if (ModelState.IsValid)
            {
                db.Facturas.Add(factura);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return Json("Factura creada con éxito");
            }
            return View(factura);
        }

        // GET: Factura/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Factura factura = db.Facturas.Find(id);
            GuiasAsignadasData(factura.ID);
            PagosAsignadosData(factura.ID);
            if (factura == null)
            {
                return HttpNotFound();
            }
            return View(factura);
        }

        // POST: Factura/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Establecimiento,PuntoEmision,Secuencial,FechaEmision,Subtotal,Impuesto,Total")] Factura factura, string[] guiasSeleccionadas, string[] pagosSeleccionados)
        {
            if (ModelState.IsValid)
            {
                var facturaToUpdate = db.Facturas
                   .Include(i => i.Guias)
                   .Include(i => i.Pagos)
                   .Where(i => i.ID == factura.ID)
                   .Single();

                db.Entry(facturaToUpdate).State = EntityState.Modified;
                ActualizarFactura(guiasSeleccionadas, pagosSeleccionados, facturaToUpdate);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return Json("Factura actualizada con éxito");
            }
            //else {
            //   Response.StatusCode = (int)HttpStatusCode.BadRequest;
            //   return Json("Model is not valid");
            //}
            return View(factura);
        }

        private void ActualizarFactura(string[] guiasSeleccionadas, string[] pagosSeleccionados, Factura factura)
        {
            if (guiasSeleccionadas == null)
            {
                factura.Guias = new List<Guia>();
            }
            else {
                var guiasSeleccionadasHS = new HashSet<string>(guiasSeleccionadas);
                var guiasDeFactura = new HashSet<int>(factura.Guias.Select(c => c.ID));
                foreach (var guia in db.Guias)
                {
                    if (guiasSeleccionadasHS.Contains(guia.ID.ToString()))
                    {
                        if (!guiasDeFactura.Contains(guia.ID))
                            factura.Guias.Add(guia);
                    }
                    else
                    {
                        if (guiasDeFactura.Contains(guia.ID))
                            factura.Guias.Remove(guia);
                    }
                }
            }

            if (pagosSeleccionados == null)
            {
                factura.Pagos = new List<Pago>();
            }
            else
            {
                var pagosSeleccionadosHS = new HashSet<string>(pagosSeleccionados);
                var pagosDeFactura = new HashSet<int>(factura.Pagos.Select(c => c.ID));
                foreach (var pago in db.Pagos)
                {
                    if (pagosSeleccionadosHS.Contains(pago.ID.ToString()))
                    {
                        if (!pagosDeFactura.Contains(pago.ID))
                            factura.Pagos.Add(pago);
                    }
                    else
                    {
                        if (pagosDeFactura.Contains(pago.ID))
                            factura.Pagos.Remove(pago);
                    }
                }
            }
        }

        // GET: Factura/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Factura factura = db.Facturas.Find(id);
            if (factura == null)
            {
                return HttpNotFound();
            }
            return View(factura);
        }

        // POST: Factura/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Factura factura = db.Facturas.Find(id); 

            foreach (var itemPago in factura.Pagos)
                itemPago.Factura = null;

            foreach (var itemGuia in factura.Guias)
                itemGuia.Factura = null;

            db.Facturas.Remove(factura);

            db.SaveChanges();
            Alert("Factura eliminada con éxito", NotificationType.success);
            return RedirectToAction("Index");
        }

        private void GuiasAsignadasData(int facturaID)
        {
            var listaGuias = db.Guias.Where(s => s.Factura == null || s.Factura.ID == facturaID).OrderByDescending(s => s.FechaEnvio);
            var viewModel = new List<GuiaAsignadaData>();
            foreach (var guia in listaGuias)
            {
                viewModel.Add(new GuiaAsignadaData
                {
                    ID = guia.ID,
                    NumeroGuía = guia.NumeroGuía,
                    FechaEnvio = guia.FechaEnvio,
                    Total = guia.Total,

PruebaFact/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PruebaFact.DAL;
using PruebaFact.Models;
using PagedList;
using static PruebaFact.Models.EnumAlert;

namespace PruebaFact.Controllers
{
    public class PagoController : BaseController
    {
        private FacturaContext db = new FacturaContext();

        // GET: Pago
        public ActionResult Index(
            string sortOrder,
            string actgualIdPago,
            string busquedaIdPago,
            string actgualIdFactura,
            string busquedaIdFactura,
            int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.IdPagoSortParm = String.IsNullOrEmpty(sortOrder) ? "idpago" : "";
            ViewBag.IdFacturaSortParm = sortOrder == "idfactura" ? "idfactura_desc" : "idfactura";

            if (busquedaIdPago != null || busquedaIdFactura != null)
            {
                page = 1;
            }
            else
            {
                busquedaIdPago = actgualIdPago;
                busquedaIdFactura = actgualIdFactura;
            }

            ViewBag.actgualIdPago = busquedaIdPago;
            ViewBag.actgualIdFactura = busquedaIdFactura;

            var pagos = from s in db.Pagos
                        select s;

            if (!String.IsNullOrEmpty(busquedaIdPago))
                pagos = pagos.Where(s => s.ID.ToString().Contains(busquedaIdPago));

            if (!String.IsNullOrEmpty(busquedaIdFactura))
                pagos = pagos.Where(s => s.Factura.ID.ToString().Contains(busquedaIdFactura));

            switch (sortOrder)
            {
                case "idfactura":
                    pagos = pagos.OrderBy(s => s.Factura.ID);
                    break;
                case "idfactura_desc":
                    pagos = pagos.OrderByDescending(s => s.Factura.ID);
                    break;
                case "idpago":
                    pagos = pagos.OrderBy(s => s.ID);
                    break;
                default:
                    pagos = pagos.OrderByDescending(s => s.ID);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(pagos.ToPagedList(pageNumber, pageSize));
        }

        // GET: Pago/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pago pago = db.Pagos.Find(id);
            if (pago == null)
            {
                return HttpNotFound();
            }
            return View(pago);
        }

        // GET: Pago/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pago/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TipoPago,Valor")] Pago pago)
        {
            if (ModelState.IsValid)
            {
                db.Pagos.Add(pago);
                db.SaveChanges();
                //Alert("Pago creado con éxito", NotificationType.success);
                //return RedirectToAction("Index");
                return Json("Pago creado con éxito");
            }
            return View(pago);
        }

        // GET: Pago/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pago pago = db.Pagos.Find(id);
            if (pago == null)
            {
                return HttpNotFound();
            }
            return View(pago);
        }

        // POST: Pago/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TipoPago,Valor")] Pago pago)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pago).State = EntityState.Modified;
                db.SaveChanges();
                //Alert("Pago actualizado con éxito", NotificationType.success);
                //return RedirectToAction("Index");
                return Json("Pago actualizado con éxito");
            }
            return View(pago);
        }

        // GET: Pago/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pago pago = db.Pagos.Find(id);
            if (pago == null)
            {
                return HttpNotFound();
            }
            return View(pago);
        }

        // POST: Pago/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pago pago = db.Pagos.Find(id);
            db.Pagos.Remove(pago);
            db.SaveChanges();
            Alert("PAgo eliminado con éxito", NotificationType.success);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PruebaFact/Views/Pago/Create.cshtml
@model PruebaFact.Models.Pago

@{
    ViewBag.Title = "Create";
}

<h3>Agregar Pago</h3>

<link href="~/Content/sweetalert2.css" rel="stylesheet" />
<script src="~/Scripts/sweetalert2.js"></script>

@*@using (Html.BeginForm()) *@
@using (Html.BeginForm("Create", "Pago", FormMethod.Post, new { id = "PagoAddForm", name = "PagoAddForm", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TipoPago, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoPago, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoPago, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnPagoAddSubmit" value="Guardar" class="btn btn-primary" />
                @*@Html.ActionLink("Regresar", "Index", "", new { @class = "btn btn-info" })*@
                <button type="button" class="btn btn-info" onclick="history.back();">Regresar</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnPagoAddSubmit').click(function () {
                if ($("#PagoAddForm").valid()) {
                    $('#PagoAddForm').submit();
                }
                else {
                    return false;
                }
            });

            $("#PagoAddForm").on("submit", function (event) {
                event.preventDefault();
                $('#btnPagoAddSubmit').attr('disabled', 'disabled');
                var url = $(this).attr("action");
                var formData = $(this).serialize();
                $.ajax({
                    url: url,
                    type: "POST",
                    data: formData,
                    dataType: "json",
                    success: function (response) {
                        Swal.fire({
                            title: '',
                            text: JSON.stringify(response),
                            icon: 'success',
                            allowOutsideClick: false,
                            allowEscapeKey: false,
                            allowEnterKey: false
                        }).then(() => {
                            //window.location.href = '/Pago';
                            window.location.href = document.referrer.replace(window.location.origin, '');
                        });
                    },
                    error: function (response) {
                        Swal.fire({
                            title: '',
                            text: 'Error al crear el Pago',
                            icon: 'error',
                            allowOutsideClick: false,
                            allowEscapeKey: false,
                            allowEnterKey: false
                        });
                    },
                    complete: function () {
                        $('#btnPagoAddSubmit').removeAttr('disabled');
                    }
                })
            });

            function regresar() {
                alert(document.referrer); return false;
            }

        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

PruebaFact/Views/Pago/Delete.cshtml
@model PruebaFact.Models.Pago

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar Pago</h2>

<h3>¿Seguro quieres eliminar estea Pago?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoPago)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPago)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-primary" />
            @Html.ActionLink("Regresar", "Index", "", new { @class = "btn btn-info" })
        </div>
    }
</div>

PruebaFact/Views/Pago/Details.cshtml
@model PruebaFact.Models.Pago

@{
    ViewBag.Title = "Details";
}

<h3>Detalle Pago</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoPago)
        </dt>

        <dd>
            @Html.ActionLink(" " + Model.TipoPago, "Edit", new { id = Model.ID }, new { @class = "glyphicon glyphicon-pencil" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        @if (Model.Factura != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Factura.ID)
            </dt>

            <dd>

                @Html.ActionLink(" " + Model.Factura.ID.ToString(), "Details", "Factura", new { id = Model.Factura.ID }, new { @class = "glyphicon glyphicon-eye-open" })
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Regresar", "Index", "", new { @class = "btn btn-info" })
</p>

PruebaFact/Views/Pago/Edit.cshtml
@model PruebaFact.Models.Pago

@{
    ViewBag.Title = "Edit";
}

<h3>Editar Pago</h3>

<link href="~/Content/sweetalert2.css" rel="stylesheet" />
<script src="~/Scripts/sweetalert2.js"></script>

@*@using (Html.BeginForm()) *@
@using (Html.BeginForm("Edit", "Pago", FormMethod.Post, new { id = "PagoEditForm", name = "PagoEditForm", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TipoPago, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoPago, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoPago, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnPagoEditSubmit" value="Guardar" class="btn btn-primary" />
                @*@Html.ActionLink("Regresar", "Index", "", new { @class = "btn btn-info" })*@
                <button type="button" class="btn btn-info" onclick="history.back();">Regresar</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnPagoEditSubmit').click(function () {
                if ($("#PagoEditForm").valid()) {
                    $('#PagoEditForm').submit();
                }
                else {
                    return false;
                }
            });

            $("#PagoEditForm").on("submit", function (event) {
                event.preventDefault();
                $('#btnPagoEditSubmit').attr('disabled', 'disabled');
                var url = $(this).attr("action");
                var formData = $(this).serialize();
                $.ajax({
                    url: url,
                    type: "POST",
                    data: formData,
                    dataType: "json",
                    success: function (response) {
                        Swal.fire({
                            title: '',
                            text: JSON.stringify(response),
                            icon: 'success',
                            allowOutsideClick: false,
                            allowEscapeKey: false,
                            allowEnterKey: false
                        }).then(() => {
                            window.location.href = document.referrer.replace(window.location.origin, '');
                        });
                    },
                    error: function (response) {
                        Swal.fire({
                            title: '',
                            text: 'Error al editar el Pago',
                            icon: 'error',
                            allowOutsideClick: false,
                            allowEscapeKey: false,
                            allowEnterKey: false
                        });
                    },
                    complete: function () {
                        $('#btnPagoEditSubmit').removeAttr('disabled');
                    }
                })
            });

            function regresar() {
                alert(document.referrer); return false;
            }

        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

PruebaFact/Views/Pago/Index.cshtml
@model PagedList.IPagedList<PruebaFact.Models.Pago>
@using PagedList.Mvc;
@using System.Web;

@{
    ViewBag.Title = "Index";
}

<h2>Pagos</h2>

<p>
    <a href="@Url.Action("Create", "Pago")" class="btn btn-primary">
        <i class="glyphicon glyphicon-plus"></i>
        <strong>Agregar</strong>
    </a>
</p>
@using (Html.BeginForm("Index", "Pago", FormMethod.Get))
{
    <p>
        Buscar por pago: @Html.TextBox("busquedaIdPago", ViewBag.actgualIdPago as string)
        Buscar por Factura: @Html.TextBox("busquedaIdFactura", ViewBag.actgualIdFactura as string)
        <input type="submit" value="Buscar" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink(HttpUtility.HtmlDecode(Html.DisplayNameFor(model => model.FirstOrDefault().ID).ToHtmlString()), "Index", new { sortOrder = ViewBag.IdPagoSortParm, actgualIdPago = ViewBag.actgualIdPago, actgualIdFactura = ViewBag.actgualIdFactura })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TipoPago)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Valor)
        </th>
        <th>
            @Html.ActionLink(HttpUtility.HtmlDecode(Html.DisplayNameFor(model => model.FirstOrDefault().Factura.ID).ToHtmlString()), "Index", new { sortOrder = ViewBag.IdFacturaSortParm, actgualIdPago = ViewBag.actgualIdPago, actgualIdFactura = ViewBag.actgualIdFactura })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.ActionLink(" " + item.ID, "Edit", new { id = item.ID }, new { @class = "glyphicon glyphicon-pencil" })
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TipoPago)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Valor)
    </td>
    <td>
        @if (item.Factura != null)
        {
            @Html.ActionLink(item.Factura.ID.ToString(), "Details", "Factura", new { id = item.Factura.ID }, null)
        }
    </td>
    <td>
        @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "glyphicon glyphicon-eye-open" })
        @*@Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "glyphicon glyphicon-trash", onclick = "return confirm('Are you sure you want to remove " + @item.ID + " to list ?');" })*@
        @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "glyphicon glyphicon-trash" })
    </td>
</tr>
    }
</table>
<br />
Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, actgualIdPago = ViewBag.actgualIdPago, actgualIdFactura = ViewBag.actgualIdFactura }))