PruebaFact/Models/Guia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PruebaFact.Models
{
    public class Guia
    {
        [Required, Display(Name = "Id Guía")]
        public int ID { get; set; }

        [Required, StringLength(10), Display(Name = "Nro Guía")]
        public string NumeroGuía { get; set; }
        
        [Required, DataType(DataType.Date), Display(Name = "Fecha de envío")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaEnvio { get; set; }

        [Required, StringLength(100), Display(Name = "País de origen")]
        public string PaisOrigen { get; set; }

        [Required, StringLength(100), Display(Name = "Nombre Remitente")]
        [RegularExpression(@"^[A-Z a-z0-9ÑñáéíóúÁÉÍÓÚ\\-\\_]+$", ErrorMessage = "El Nombre debe ser alfanumérico.")]
        public string NombreRemitente { get; set; }

        [Required, StringLength(100), Display(Name = "Dirección Remitente")]
        public string DireccionRemitente { get; set; }

        [StringLength(50), Display(Name = "Teléfono Remitente")]
        public string TelefonoRemitente { get; set; }

        [StringLength(50), Display(Name = "Email Remitente")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Dirección de Correo electrónico incorrecta.")]
        public string EmailRemitente { get; set; }

        [Required, StringLength(100), Display(Name = "País de destino")]
        public string PaisDestino { get; set; }

        [Required, StringLength(100), Display(Name = "Nombre Destinatario")]
        [RegularExpression(@"^[A-Z a-z0-9ÑñáéíóúÁÉÍÓÚ\\-\\_]+$", ErrorMessage = "El Nombre debe ser alfanumérico.")]
        public string NombreDestinatario { get; set; }

        [Required, StringLength(100), Display(Name = "Dirección Destinatario")]
        public string DireccionDestinatario { get; set; }

        [StringLength(50), Display(Name = "Teléfono Destinatario")]
        public string TelefonoDestinatario { get; set; }

        [StringLength(50), Display(Name = "Email Destinatario")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Dirección de Correo electrónico incorrecta.")]
        public string EmailDestinatario { get; set; }

        [Required, DataType(DataType.Currency), Display(Name = "Total")]
        public Decimal Total { get; set; }

        public virtual Factura Factura { get; set; }

    }
}

PruebaFact/Controllers/GuiaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PruebaFact.DAL;
using PruebaFact.Models;
using PagedList;
using static PruebaFact.Models.EnumAlert;

namespace PruebaFact.Controllers
{
    public class GuiaController : BaseController
    {
        private FacturaContext db = new FacturaContext();

        // GET: Guia
        public ActionResult Index(
            string sortOrder, 
            string actgualNumeroGuia, 
            string busquedaNumeroGuia, 
            string actgualIdFactura, 
            string busquedaIdFactura, 
            int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FechaEnvioSortParm = String.IsNullOrEmpty(sortOrder) ? "FechaEnvio" : "";
            ViewBag.NumeroGuiaSortParm = sortOrder == "NumeroGuia" ? "NumeroGuia_desc" : "NumeroGuia";
            ViewBag.IdFacturaSortParm = sortOrder == "IdFactura" ? "IdFactura_desc" : "IdFactura";


            if (busquedaNumeroGuia != null || busquedaIdFactura != null)
            {
                page = 1;
            }
            else
            {
                busquedaNumeroGuia = actgualNumeroGuia;
                busquedaIdFactura = actgualIdFactura;
            }

            ViewBag.actgualNumeroGuia = busquedaNumeroGuia;
            ViewBag.actgualNumeroFactura = busquedaIdFactura;

            var guias = from s in db.Guias
                           select s;

            if (!String.IsNullOrEmpty(busquedaNumeroGuia))
                guias = guias.Where(s => s.NumeroGuía.Contains(busquedaNumeroGuia));

            if (!String.IsNullOrEmpty(busquedaIdFactura))
                guias = guias.Where(s => s.Factura.ID.ToString().Contains(busquedaIdFactura));

            switch (sortOrder)
            {
                case "NumeroGuia":
                    guias = guias.OrderBy(s => s.NumeroGuía);
                    break;
                case "NumeroGuia_desc":
                    guias = guias.OrderByDescending(s => s.NumeroGuía);
                    break;
                case "IdFactura":
                    guias = guias.OrderBy(s => s.Factura.ID);
                    break;
                case "IdFactura_desc":
                    guias = guias.OrderByDescending(s => s.Factura.ID);
                    break;
                case "FechaEnvio":
                    guias = guias.OrderBy(s => s.FechaEnvio);
                    break;
                default:
                    guias = guias.OrderByDescending(s => s.FechaEnvio);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(guias.ToPagedList(pageNumber, pageSize));
        }

        // GET: Guia/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guia guia = db.Guias.Find(id);
            if (guia == null)
            {
                return HttpNotFound();
            }
            return View(guia);
        }

        // GET: Guia/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Guia/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NumeroGuía,FechaEnvio,PaisOrigen,NombreRemitente,DireccionRemitente,TelefonoRemitente,EmailRemitente,PaisDestino,NombreDestinatario,DireccionDestinatario,TelefonoDestinatario,EmailDestinatario,Total")] Guia guia)
        {
            if (ModelState.IsValid)
            {
                db.Guias.Add(guia);
                db.SaveChanges();
                //Alert("Guía creada con éxito", NotificationType.success);
                //return RedirectToAction("Index");
                return Json("Guía creada con éxito");
            }
            return View(guia);
        }

        // GET: Guia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guia guia = db.Guias.Find(id);
            if (guia == null)
            {
                return HttpNotFound();
            }
            return View(guia);
        }

        // POST: Guia/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NumeroGuía,FechaEnvio,PaisOrigen,NombreRemitente,DireccionRemitente,TelefonoRemitente,EmailRemitente,PaisDestino,NombreDestinatario,DireccionDestinatario,TelefonoDestinatario,EmailDestinatario,Total")] Guia guia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(guia).State = EntityState.Modified;
                db.SaveChanges();

                var guiaToUpdate = db.Guias
                   .Include(i => i.Factura)
                   .Where(i => i.ID == guia.ID)
                   .Single();

                Factura factura = guiaToUpdate.Factura;
                if (factura != null)
                    FacturaRecalcular(factura);

                db.SaveChanges();
                //Alert("Guía actualizada con éxito", NotificationType.success);
                //return RedirectToAction("Index");
                return Json("Guía actualizada con éxito");
            }
            return View(guia);
        }

        // GET: Guia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guia guia = db.Guias.Find(id);
            if (guia == null)
            {
                return HttpNotFound();
            }
            return View(guia);
        }

        // POST: Guia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Guia guia = db.Guias.Find(id);

            Factura factura = guia.Factura;

            db.Guias.Remove(guia);

            if (factura != null) 
                FacturaRecalcular(factura);

            db.SaveChanges();
            Alert("Guía eliminada con éxito", NotificationType.success);
            return RedirectToAction("Index");
        }

        private void FacturaRecalcular(Factura factura) {
            decimal subtotal;
            decimal impuesto;
            decimal totalactual;
            decimal total;
            decimal totaldif;

            totalactual = factura.Total;
            totaldif = 0;
            subtotal = 0;

            foreach (var guia in factura.Guias)
                subtotal += Math.Round(guia.Total, 2);

            impuesto = Math.Round((subtotal * 12) / 100, 2);
            total = Math.Round(subtotal  + impuesto, 2);

            factura.Subtotal = subtotal;
            factura.Impuesto = impuesto;
            factura.Total = total;

            totaldif = total - totalactual;
            IEnumerable<Pago> pagos = new List<Pago>();
            if (totaldif < 0)
                pagos = factura.Pagos.OrderByDescending(s => s.Valor);
            else
                pagos = factura.Pagos.OrderBy(s => s.Valor);

            foreach (var pago in pagos)
            {
                decimal valorActual = pago.Valor;
                pago.Valor = valorActual + totaldif;
                if (pago.Valor < 0)
                {
                    totaldif = pago.Valor;
                    pago.Valor = 0;
                }
                else 
                    break;
            }

            //Elimono todos los pagos en cero (0)
            pagos = pagos.Where(s => s.Valor.Equals(0));
            foreach (var pago in pagos)
                factura.Pagos.Remove(pago);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PruebaFact/Views/Guia/Create.cshtml
@model PruebaFact.Models.Guia

@{
    ViewBag.Title = "Create";
}

<h3>Agregar Guía</h3>

<link href="~/Content/sweetalert2.css" rel="stylesheet" />
<script src="~/Scripts/sweetalert2.js"></script>

@*@using (Html.BeginForm()) *@
@using (Html.BeginForm("Create", "Guia", FormMethod.Post, new { id = "GuiaAddForm", name = "GuiaAddForm", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NumeroGuía, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroGuía, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroGuía, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEnvio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEnvio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEnvio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaisOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaisOrigen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaisOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreRemitente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreRemitente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreRemitente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DireccionRemitente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DireccionRemitente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DireccionRemitente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoRemitente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoRemitente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoRemitente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailRemitente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailRemitente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailRemitente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaisDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaisDestino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaisDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreDestinatario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreDestinatario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreDestinatario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DireccionDestinatario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DireccionDestinatario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DireccionDestinatario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoDestinatario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoDestinatario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoDestinatario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailDestinatario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailDestinatario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailDestinatario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnGuiaAddSubmit" value="Guardar" class="btn btn-primary" />
                @*@Html.ActionLink("Regresar", "Index", "", new { @class = "btn btn-info" })*@
                <button type="button" class="btn btn-info" onclick="history.back();">Regresar</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnGuiaAddSubmit').click(function () {
                if ($("#GuiaAddForm").valid()) {
                    $('#GuiaAddForm').submit();
                }
                else {
                    return false;
                }
            });

            $("#GuiaAddForm").on("submit", function (event) {
                event.preventDefault();
                $('#btnGuiaAddSubmit').attr('disabled', 'disabled');
                var url = $(this).attr("action");
                var formData = $(this).serialize();
                $.ajax({
                    url: url,
                    type: "POST",
                    data: formData,
                    dataType: "json",
                    success: function (response) {
                        Swal.fire({
                            title: '',
                            text: JSON.stringify(response),
                            icon: 'success',
                            allowOutsideClick: false,
                            allowEscapeKey: false,
                            allowEnterKey: false
                        }).then(() => {
                            window.location.href = document.referrer.replace(window.location.origin, '');
                        });
                    },
                    error: function (response) {
                        Swal.fire({
                            title: '',
                            text: 'Error al crear la Guía',
                            icon: 'error',
                            allowOutsideClick: false,
                            allowEscapeKey: false,
                            allowEnterKey: false
                        });
                    },
                    complete: function () {
                        $('#btnGuiaAddSubmit').removeAttr('disabled');
                    }
                })
            });

            function regresar() {
                alert(document.referrer); return false;
            }
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

PruebaFact/Views/Guia/Edit.cshtml
@model PruebaFact.Models.Guia

@{
    ViewBag.Title = "Edit";
}

<h3>Editar Guía</h3>

<link href="~/Content/sweetalert2.css" rel="stylesheet" />
<script src="~/Scripts/sweetalert2.js"></script>

@*@using (Html.BeginForm()) *@
@using (Html.BeginForm("Edit", "Guia", FormMethod.Post, new { id = "GuiaEditForm", name = "GuiaEditForm", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroGuía, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroGuía, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroGuía, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEnvio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEnvio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEnvio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaisOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaisOrigen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaisOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreRemitente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreRemitente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreRemitente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DireccionRemitente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DireccionRemitente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DireccionRemitente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoRemitente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoRemitente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoRemitente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailRemitente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailRemitente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailRemitente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaisDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaisDestino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaisDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreDestinatario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreDestinatario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreDestinatario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DireccionDestinatario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DireccionDestinatario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DireccionDestinatario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoDestinatario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoDestinatario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoDestinatario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailDestinatario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailDestinatario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailDestinatario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnGuiaEditSubmit" value="Guardar" class="btn btn-primary" />
                @*@Html.ActionLink("Regresar", "Index", "", new { @class = "btn btn-info" })*@
                <button type="button" class="btn btn-info" onclick="history.back();">Regresar</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnGuiaEditSubmit').click(function () {
                if ($("#GuiaEditForm").valid()) {
                    $('#GuiaEditForm').submit();
                }
                else {
                    return false;
                }
            });

            $("#GuiaEditForm").on("submit", function (event) {
                event.preventDefault();
                $('#btnGuiaEditSubmit').attr('disabled', 'disabled');
                var url = $(this).attr("action");
                var formData = $(this).serialize();
                $.ajax({
                    url: url,
                    type: "POST",
                    data: formData,
                    dataType: "json",
                    success: function (response) {
                        Swal.fire({
                            title: '',
                            text: JSON.stringify(response),
                            icon: 'success',
                            allowOutsideClick: false,
                            allowEscapeKey: false,
                            allowEnterKey: false
                        }).then(() => {
                            window.location.href = document.referrer.replace(window.location.origin, '');
                        });
                    },
                    error: function (response) {
                        Swal.fire({
                            title: '',
                            text: 'Error al editar la Guía',
                            icon: 'error',
                            allowOutsideClick: false,
                            allowEscapeKey: false,
                            allowEnterKey: false
                        });
                    },
                    complete: function () {
                        $('#btnGuiaEditSubmit').removeAttr('disabled');
                    }
                })
            });

            function regresar() {
                alert(document.referrer); return false;
            }
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}